# Example silver-dollar.rb configuration file
{
    config: {
        project_dir: File.expand_path('~/Projects'),
        pull_branches: ['master', 'develop'],
        basis_branch: 'develop',
    },
    projects: [
        {library: 'shutdown-services', always_build: true},
        {library: 'config'},
        {library: 'authentication'},
        {library: 'bizops-parent'},
        {library: 'alg-ota-support'},
        {library: 'uds-metrics-cdi'},
        {library: 'uap-common'},
        {library: 'alg-error'},
        {library: 'alg-domain'},
        {library: 'alg-test-utils'},
        {library: 'ari-client'},
        {library: 'alg-common-data'},
        {library: 'alg-data', mvn_flags: ['-Pclean-db']},
        {library: 'alg-data-load', mvn_flags: ['-Pautopatch']},
        {library: 'booking-data', repo: 'core'},
        {library: 'pricing-data'},
        {library: 'ari-data'},
        {library: 'bizops-client'},
        {library: 'hbsi'},
        {library: 'verticalbooking', repo: 'core'},
        {library: 'pricing-client'},
        {service: 'bizops-service', archive: 'bizops.war'},
        {service: 'bizops', archive: 'alg.war'},
        {service: 'ari-service', archive: 'ari.war'},
        {service: 'geo', wlp: 'core', restart: false},
        {service: 'product', wlp: 'core', restart: false},
        {service: 'hotel', wlp: 'core', restart: false},
        {service: 'pricing', restart: false},
        {library: 'trip'},
        {library: 'package-svc'},
        {library: 'user'},
    ]
}